language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

# for tincanradar
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6
      - liblapack-dev
      - libfftw3-dev

before_install:
    - pip -q install coveralls

install: pip -q install -e .

script: coverage run tests/test.py -v

after_success: coveralls

